/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metime;

/**
 *
 * @author DeeShalz
 */
public class AddChoiceUI extends javax.swing.JFrame {
    private  NavigationCntl parentNavigationCntl;
    private NavigationOption selectedOption;
    private AddCntl parentAddCntl;
    /**
     * Creates new form AddChoiceUI
     */
 

    public AddChoiceUI(AddCntl parentAddCntl) {
        parentNavigationCntl = this.parentNavigationCntl;
        parentAddCntl = this.parentAddCntl;
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        eventRadioButton = new javax.swing.JRadioButton();
        contactRadioButton = new javax.swing.JRadioButton();
        backButton = new javax.swing.JButton();
        goButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eventRadioButton.setText("ADD EVENT");

        contactRadioButton.setText("ADD CONTACT");
        contactRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactRadioButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");

        goButton.setText("Go");

        exitButton.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactRadioButton)
                    .addComponent(eventRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(exitButton)
                .addGap(55, 55, 55)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(goButton)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(eventRadioButton)
                .addGap(32, 32, 32)
                .addComponent(contactRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(goButton)
                    .addComponent(exitButton))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactRadioButtonActionPerformed
            selectedOption = NavigationOption.CONTACT;
    }//GEN-LAST:event_contactRadioButtonActionPerformed
    private void eventRadioButtonActionPerformed(java.awt.event.ActionEvent evt){
        selectedOption = NavigationOption.EVENT;
    }
    private void goButtonActionPerformed(java.awt.event.ActionEvent evt){
        switch(selectedOption){
            case CONTACT:
                this.setVisible(false);
                this.parentAddCntl.requestContactUI();
                break;
            case SEARCH:
                this.setVisible(false);
                this.parentAddCntl.requestEventUI();
        }
    }
     private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        System.exit(0);
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddChoiceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddChoiceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddChoiceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddChoiceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddChoiceUI().setVisible(true);
            }
        }); */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton contactRadioButton;
    private javax.swing.JRadioButton eventRadioButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton goButton;
    // End of variables declaration//GEN-END:variables

}
