/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metime.views;

import metime.controllers.ContactCntl;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import metime.models.Contact;

/**
 *
 * @author DeeShalz
 */
public class ContactUI extends javax.swing.JFrame {

    private final ContactCntl theContactCntl;
    private final Contact theContactToEdit;

    /**
     *
     * @param newContactCntl
     */
    public ContactUI(ContactCntl newContactCntl) {
        this.theContactCntl = newContactCntl;
        construct();
        initComponents();
        deleteButton.setVisible(false);
        theContactToEdit = null;
    }

    /**
     *
     * @param newContactCntl
     * @param theContactToEdit
     */
    public ContactUI(ContactCntl newContactCntl, Contact theContactToEdit) {
        this.theContactCntl = newContactCntl;
        construct();
        initComponents();
        this.theContactToEdit = theContactToEdit;
        firstName.setText(theContactToEdit.getFirstName());
        lastName.setText(theContactToEdit.getLastName());
        phoneNum.setText(theContactToEdit.getPhone());
        emailField.setText(theContactToEdit.getEmail());
        deleteButton.setVisible(true);
    }

    private void construct() {
        pack();
        setTitle("Create, Read, Update, & Delete Events");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contactName = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        contactPhone = new javax.swing.JLabel();
        phoneNum = new javax.swing.JTextField();
        contactEmail = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        saveContactButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contactName.setText("Contact Name: ");

        firstName.setText("First Name");

        lastName.setText("Last Name");

        contactPhone.setText("Contact Phone: ");

        phoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumActionPerformed(evt);
            }
        });

        contactEmail.setText("Contact Email: ");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        saveContactButton.setText("Save");
        saveContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveContactButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactPhone)
                            .addComponent(contactEmail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(phoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contactName)
                        .addGap(22, 22, 22)
                        .addComponent(firstName, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastName, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveContactButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactName)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactPhone)
                    .addComponent(phoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactEmail)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(saveContactButton)
                    .addComponent(deleteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        this.theContactCntl.getParentNavigationCntl().requestMainMenuUI();
    }//GEN-LAST:event_backButtonActionPerformed

    private void saveContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveContactButtonActionPerformed
        String newContactFirstName = this.firstName.getText();
        String newContactLastName = this.lastName.getText();
        String newContactEmail = this.emailField.getText();
        String newContactPhone = this.phoneNum.getText();

        if (newContactFirstName.equalsIgnoreCase("First Name") || newContactLastName.equalsIgnoreCase("Last Name")
                || newContactEmail.length() == 0 || newContactFirstName.length() == 0 || newContactLastName.length() == 0) {
            JOptionPane.showMessageDialog(null, "Please ensure that your contact has a first and last name, and email address");
        } else {
            if (theContactToEdit != null) {
                theContactToEdit.setEmail(newContactEmail);
                theContactToEdit.setFirstName(newContactFirstName);
                theContactToEdit.setLastName(newContactLastName);
                theContactToEdit.setPhone(newContactPhone);
                theContactCntl.saveContactList();
                JOptionPane.showMessageDialog(null, "Edited contact.");
            } else {
                theContactCntl.addContact(new Contact(newContactFirstName, newContactLastName, newContactPhone, newContactEmail));
                JOptionPane.showMessageDialog(null, "Created contact.");
            }

            this.backButtonActionPerformed(evt);
        }
    }//GEN-LAST:event_saveContactButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (theContactToEdit != null) {
            theContactCntl.deleteContact(theContactToEdit);
            JOptionPane.showMessageDialog(null, "Contact deleted.");
            this.backButtonActionPerformed(evt);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel contactEmail;
    private javax.swing.JLabel contactName;
    private javax.swing.JLabel contactPhone;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField phoneNum;
    private javax.swing.JButton saveContactButton;
    // End of variables declaration//GEN-END:variables

}
